version: "3.9"

services:
  mongodb:
    image: mongo:6.0.1
    restart: "no"
    ports:
      - ${HERMES_MONGODB_PORT:-27018}:27017
    # config user auth for mongo in the future
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: ${HERMES_MONGODB_ROOT_USER_NAME}
  #      MONGO_INITDB_ROOT_PASSWORD: ${HERMES_MONGODB_ROOT_USER_PASSWORD}
  #      MONGO_INITDB_SCRIPTS: /docker-entrypoint-initdb.d/init.js